### ISSUE TITLE
Publishing on Alpine Linux's package repository

### ISSUE THREAD

**Issue by cocoliliace** [Elsa002/queercat#16]
Hi, thank you for the nice project!

Would you be interested in adding this project to the [Alpine Linux's package repository](https://pkgs.alpinelinux.org/packages)? I can help with creating the [`APKBUILD` file](https://wiki.alpinelinux.org/wiki/APKBUILD_Reference). One advantage of having it maintained by the upstream is that whenever you make an update, you know to update the `APKBUILD` so the Alpine package will always be up to date.

If you are not interested in doing this, would you mind if I maintain it? And then you can flag the package as out of date whenever you make an update and I will update it :)

**Comment by cocoliliace** [comment]
Actually, I figured that I can use the "watch" feature on github to get notified by new pushes to the repo, so I don't mind maintaining it. The [project license](https://github.com/Elsa002/queercat/blob/551c1994e537c582c4a2644d3c4c6ecd863dd2b1/LICENSE) allows us to redistribute the code, so I've went ahead and submitted [a patch to the alpine package repository](https://lists.alpinelinux.org/~alpine/aports/patches/4159).

Let me know if you'd like to take over the maintainership. I will keep this issue open until the package gets accepted by the upstream :)

**Comment by cocoliliace** [comment]
Hi, my request got rejected because I am building from a custom commit rather than a release. [The alpine developers are asking for a release](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44919#note_295169). Can you please [make a release on github](https://github.com/Elsa002/queercat/releases)? I'd help but I don't have the permission.

**Comment by Elsa002** [comment]
Sorry for late reply, added a release

**Comment by cocoliliace** [comment]
Thank you. The package is now published: https://pkgs.alpinelinux.org/packages?name=queercat
