### ISSUE TITLE
Please may you add a license?

### ISSUE THREAD

**Issue by Minion3665** [Elsa002/queercat#8]
I'd like to package this for my distribution, but for that it needs a license. 

If you're not sure what license to use, I'd suggest either MIT or GPLv3-or-later. [Here's a site with more info on license choices](https://choosealicense.com/)

**Comment by LunarEclipse363** [comment]
Seconding this.

I just created an [AUR package for queercat](https://aur.archlinux.org/packages/queercat-git) and although packages with an unknown license are allowed there, it would be preferable to have a license.

In addition to the licenses suggested above, if you want to allow any use of the project like lolcat does, you could just go with [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) which is basically public domain.
I can also recommend [this tool from the European Commission website](https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-find-and-compare-software-licenses) for choosing an open source license depending on your requirements.

**Comment by Elsa002** [comment]
Added
